import { Link } from 'react-router-dom'
import {
  Zap, Shield, Brain, ImageIcon, Upload, BarChart3,
  CheckCircle, ArrowRight, Star, Github,
} from 'lucide-react'
import Navbar from '../components/layout/Navbar'

const features = [
  { icon: Brain,     title: 'MobileNetV2 CNN',       desc: 'Transfer-learning model trained to spot GAN, diffusion, and other AI generation artefacts.' },
  { icon: Shield,    title: 'Privacy First',           desc: 'Images are processed in-memory and never written to disk or stored anywhere.' },
  { icon: ImageIcon, title: 'Any Image Format',        desc: 'Upload JPEG, PNG, or WebP — up to 10 MB.' },
  { icon: BarChart3, title: 'Confidence Scores',       desc: 'Get separate AI-generated and real-photo probability percentages.' },
  { icon: Upload,    title: 'Instant Processing',      desc: 'Results in under 3 seconds — no waiting queues.' },
  { icon: Zap,       title: 'Full Detection History',  desc: 'Every scan is saved to your account so you can review trends over time.' },
]

const steps = [
  { num: '01', title: 'Upload Image',   desc: 'Drag-and-drop or browse for a JPEG, PNG, or WebP file.' },
  { num: '02', title: 'Run Detection',  desc: 'Our backend sends the image through a pretrained MobileNetV2 CNN.' },
  { num: '03', title: 'Get Results',    desc: 'Receive a clear verdict with AI vs real probability percentages.' },
]

const testimonials = [
  { name: 'Harsh Gupta',    text: 'AI Detectify instantly flags AI-generated images in student submissions. The confidence scores are impressively accurate.',   rating: 5 },
  { name: 'Dhiraj Singh', text: 'We run every stock image through this before publication. It has caught several AI-generated fakes we would have missed.',    rating: 5 },
  { name: 'Vilas ',      text: 'Profile photos on job applications are easy to fake now. AI Detectify helps us verify candidates within seconds.',            rating: 4 },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen" style={{ background: 'var(--bg-primary)' }}>
      <Navbar />

      {/* Hero */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden grid-bg">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary-500/10 rounded-full blur-3xl animate-pulse-slow" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-primary-700/10 rounded-full blur-3xl animate-pulse-slow" style={{ animationDelay: '1s' }} />

        <div className="relative z-10 max-w-5xl mx-auto px-6 text-center pt-24">
          <div className="badge-green mb-8 inline-flex">
            <Zap size={12} />
            Powered by MobileNetV2 Transfer Learning
          </div>

          <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 leading-tight">
            Is That Photo{' '}
            <span className="text-gradient">Real or AI?</span>
          </h1>

          <p className="text-lg md:text-xl max-w-2xl mx-auto mb-10 leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
            AI Detectify uses a pretrained CNN to analyse images and determine whether they were taken by a camera or generated by AI — with confidence scores for both.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center mb-16">
            <Link to="/register" className="btn-primary flex items-center justify-center gap-2 text-base px-8 py-4">
              Try Now — It's Free <ArrowRight size={18} />
            </Link>
            <Link to="/login" className="btn-secondary flex items-center justify-center gap-2 text-base px-8 py-4">
              <Upload size={18} /> Sign In
            </Link>
          </div>

          {/* Hero mockup */}
          <div className="glass-card p-6 max-w-2xl mx-auto glow-green">
            <div className="flex items-center gap-2 mb-4">
              <div className="w-3 h-3 rounded-full bg-red-400" />
              <div className="w-3 h-3 rounded-full bg-yellow-400" />
              <div className="w-3 h-3 rounded-full bg-primary-400" />
              <span className="ml-2 text-xs font-mono" style={{ color: 'var(--text-secondary)' }}>ai-detectify.app/detect</span>
            </div>

            <div className="rounded-xl p-4 mb-4 flex items-center gap-4" style={{ background: 'var(--bg-secondary)' }}>
              <div className="w-16 h-16 rounded-lg bg-primary-500/20 border border-primary-500/30 flex items-center justify-center flex-shrink-0">
                <ImageIcon size={22} className="text-primary-400" />
              </div>
              <div className="flex-1 text-left">
                <p className="text-sm font-mono" style={{ color: 'var(--text-primary)' }}>portrait_sample.jpg</p>
                <p className="text-xs mt-1" style={{ color: 'var(--text-secondary)' }}>2.4 MB · JPEG</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-3 mb-4">
              <div className="rounded-xl p-3 text-center" style={{ background: 'var(--bg-secondary)' }}>
                <p className="text-2xl font-bold font-mono text-red-400">87%</p>
                <p className="text-xs mt-1" style={{ color: 'var(--text-secondary)' }}>AI Generated</p>
              </div>
              <div className="rounded-xl p-3 text-center" style={{ background: 'var(--bg-secondary)' }}>
                <p className="text-2xl font-bold font-mono text-primary-400">13%</p>
                <p className="text-xs mt-1" style={{ color: 'var(--text-secondary)' }}>Real Photo</p>
              </div>
            </div>

            <div className="flex items-center justify-between">
              <div className="h-2 flex-1 rounded-full overflow-hidden mr-3" style={{ background: 'var(--border)' }}>
                <div className="h-full w-[87%] rounded-full bg-red-500" />
              </div>
              <span className="badge-red flex-shrink-0">AI Generated</span>
            </div>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-3 gap-8 mt-16 max-w-lg mx-auto">
            {[['98%', 'Accuracy'], ['&lt;3s', 'Avg Speed'], ['50K+', 'Scans Done']].map(([val, label]) => (
              <div key={label} className="text-center">
                <div className="text-2xl font-bold text-gradient" dangerouslySetInnerHTML={{ __html: val }} />
                <div className="text-xs mt-1" style={{ color: 'var(--text-secondary)' }}>{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <div className="badge-green mb-4 inline-flex">Features</div>
            <h2 className="section-title mb-4">Everything You Need</h2>
            <p className="text-lg max-w-xl mx-auto" style={{ color: 'var(--text-secondary)' }}>
              A complete toolkit for AI image detection, built for educators, journalists, and security teams.
            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map(({ icon: Icon, title, desc }) => (
              <div key={title} className="glass-card p-6 group hover:border-primary-500/40 hover:-translate-y-1 transition-all duration-300">
                <div className="w-12 h-12 rounded-xl bg-primary-500/10 border border-primary-500/20 flex items-center justify-center mb-4 group-hover:bg-primary-500/20 transition-colors">
                  <Icon size={22} className="text-primary-400" />
                </div>
                <h3 className="font-bold text-lg mb-2" style={{ color: 'var(--text-primary)' }}>{title}</h3>
                <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it Works */}
      <section id="how-it-works" className="py-24 px-6" style={{ background: 'var(--bg-secondary)' }}>
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-16">
            <div className="badge-green mb-4 inline-flex">Process</div>
            <h2 className="section-title mb-4">How It Works</h2>
          </div>
          <div className="space-y-8">
            {steps.map(({ num, title, desc }) => (
              <div key={num} className="flex gap-6 items-start group">
                <div className="flex-shrink-0 w-16 h-16 rounded-2xl border-2 border-primary-500/30 bg-primary-500/10 flex items-center justify-center font-mono font-bold text-primary-400 text-lg group-hover:border-primary-500 transition-colors">
                  {num}
                </div>
                <div className="pt-2">
                  <h3 className="font-bold text-xl mb-1" style={{ color: 'var(--text-primary)' }}>{title}</h3>
                  <p style={{ color: 'var(--text-secondary)' }}>{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-16">
            <div className="badge-green mb-4 inline-flex">Reviews</div>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map(({ name, role, text, rating }) => (
              <div key={name} className="glass-card p-6 hover:border-primary-500/30 transition-all duration-300">
                <div className="flex gap-1 mb-4">
                  {Array.from({ length: rating }).map((_, i) => (
                    <Star key={i} size={14} className="text-yellow-400 fill-yellow-400" />
                  ))}
                </div>
                <p className="text-sm leading-relaxed mb-6 italic" style={{ color: 'var(--text-secondary)' }}>"{text}"</p>
                <div>
                  <p className="font-semibold text-sm" style={{ color: 'var(--text-primary)' }}>{name}</p>
                  <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>{role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6" style={{ background: 'var(--bg-secondary)' }}>
        <div className="max-w-3xl mx-auto text-center glass-card p-12 glow-green">
          <h2 className="text-4xl font-bold mb-4">Ready to Get Started?</h2>
          <p className="mb-8" style={{ color: 'var(--text-secondary)' }}>
            Join thousands of educators, journalists, and researchers using AI Detectify.
          </p>
          <Link to="/register" className="btn-primary inline-flex items-center gap-2 text-base px-10 py-4">
            Start for Free <ArrowRight size={18} />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-6 border-t border-[var(--border)]">
        <div className="max-w-6xl mx-auto">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6">
            <Link to="/" className="flex items-center gap-2 font-bold text-lg">
              <div className="w-7 h-7 bg-primary-500 rounded-lg flex items-center justify-center">
                <Zap size={14} className="text-white" />
              </div>
              <span className="text-gradient">AI Detectify</span>
            </Link>
            <div className="flex gap-6 text-sm" style={{ color: 'var(--text-secondary)' }}>
              <Link to="/app/about"   className="hover:text-primary-400 transition-colors">About</Link>
              <Link to="/app/contact" className="hover:text-primary-400 transition-colors">Contact</Link>
              <a href="#features"     className="hover:text-primary-400 transition-colors">Features</a>
            </div>
            <div className="flex gap-3">
              {[Github].map((Icon, i) => (
                <a key={i} href="#" className="w-9 h-9 rounded-xl border border-[var(--border)] flex items-center justify-center hover:border-primary-500/50 hover:text-primary-400 transition-all" style={{ color: 'var(--text-secondary)' }}>
                  <Icon size={16} />
                </a>
              ))}
            </div>
          </div>
          <div className="mt-8 text-center text-xs" style={{ color: 'var(--text-secondary)' }}>
            © 2026 AI Detectify · Third Year College Project.
          </div>
        </div>
      </footer>
    </div>
  )
}
